# Generated by Django 5.2.17 on 2026-09-30 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='palette',
            field=models.CharField(choices=[('atlas', 'Atlas'), ('osmon', 'Sky'), ('bog', 'Garden'), ('anor', 'Pomegranate')], default='atlas', max_length=10, verbose_name='colours'),
        ),
    ]
