# Generated by Django 5.2.17 on 2026-09-30 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_palette'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time_zone',
            field=models.CharField(default='Asia/Tashkent', max_length=40, verbose_name='time zone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('uz', 'Oʻzbekcha'), ('uz-cyrl', 'Ўзбекча'), ('ru', 'Русский'), ('en', 'English')], default='uz', max_length=10, verbose_name='interface language'),
        ),
    ]
