# Generated by Django 5.2.17 on 2026-09-30 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_collaboration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='palette',
        ),
    ]
