# Generated by Django 5.2.17 on 2026-09-27 13:18

import apps.genealogy.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='last name')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='patronymic')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10, verbose_name='gender')),
                ('birth_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='year of birth')),
                ('birth_month', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='month of birth')),
                ('birth_day', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='day of birth')),
                ('birth_place', models.CharField(blank=True, max_length=200, verbose_name='place of birth')),
                ('is_deceased', models.BooleanField(default=False, verbose_name='deceased')),
                ('death_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='year of death')),
                ('death_month', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='month of death')),
                ('death_day', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='day of death')),
                ('death_place', models.CharField(blank=True, max_length=200, verbose_name='place of death')),
                ('occupation', models.CharField(blank=True, max_length=200, verbose_name='occupation')),
                ('education', models.CharField(blank=True, max_length=200, verbose_name='education')),
                ('biography', models.TextField(blank=True, verbose_name='biography')),
                ('life_story', models.TextField(blank=True, verbose_name='life story')),
                ('photo', models.ImageField(blank=True, upload_to=apps.genealogy.models.photo_path, verbose_name='photo')),
                ('search_key', models.TextField(blank=True, db_index=True, default='', editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_as_father', to='genealogy.person', verbose_name='father')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_as_mother', to='genealogy.person', verbose_name='mother')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'people',
                'ordering': ['last_name', 'first_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('body', models.TextField(verbose_name='story')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='year')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='genealogy.person', verbose_name='about whom')),
            ],
            options={
                'verbose_name': 'story',
                'verbose_name_plural': 'stories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Marriage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='year of marriage')),
                ('is_divorced', models.BooleanField(default=False, verbose_name='divorced')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marriages', to=settings.AUTH_USER_MODEL)),
                ('husband', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marriages_as_husband', to='genealogy.person', verbose_name='husband')),
                ('wife', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marriages_as_wife', to='genealogy.person', verbose_name='wife')),
            ],
            options={
                'verbose_name': 'marriage',
                'verbose_name_plural': 'marriages',
                'ordering': ['year', 'id'],
                'constraints': [models.UniqueConstraint(fields=('husband', 'wife'), name='unique_marriage')],
            },
        ),
    ]
