# Generated by Django 5.2.17 on 2026-09-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='body',
            field=models.TextField(verbose_name='text'),
        ),
    ]
