# Generated by Django 5.2.17 on 2026-09-28 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0002_story_body_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='marriage',
            name='day',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='day of marriage'),
        ),
        migrations.AddField(
            model_name='marriage',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='month of marriage'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('wedding', 'Wedding'), ('engagement', 'Engagement (fotiha)'), ('pregnancy', 'Expecting a baby'), ('birth', 'Birth of a child'), ('beshik', 'Cradle celebration (beshik toʻyi)'), ('sunnat', 'Circumcision celebration (sunnat toʻyi)'), ('graduation', 'Graduation'), ('work', 'New job'), ('move', 'Moving house'), ('hajj', 'Hajj or umrah'), ('anniversary', 'Jubilee'), ('death', 'Death'), ('memorial', 'Memorial gathering (yil oshi)'), ('other', 'Other event')], default='other', max_length=20, verbose_name='type of event')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='title')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='year')),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='month')),
                ('day', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='day')),
                ('place', models.CharField(blank=True, max_length=200, verbose_name='place')),
                ('description', models.TextField(blank=True, verbose_name='details')),
                ('every_year', models.BooleanField(default=False, verbose_name='remind every year on this day')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
                ('people', models.ManyToManyField(blank=True, related_name='events', to='genealogy.person', verbose_name='who')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
                'ordering': ['-year', '-month', '-day', '-id'],
            },
        ),
    ]
