# Generated by Django 5.2.17 on 2026-09-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0003_marriage_day_marriage_month_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='burial_place',
            field=models.CharField(blank=True, max_length=250, verbose_name='place of burial'),
        ),
    ]
