# Uzbek (Cyrillic): "2026 йил 27 сентябрь".
DATE_FORMAT = r"Y \й\и\л j E"
TIME_FORMAT = "H:i"
DATETIME_FORMAT = r"Y \й\и\л j E, H:i"
YEAR_MONTH_FORMAT = r"Y \й\и\л F"
MONTH_DAY_FORMAT = "j E"
SHORT_DATE_FORMAT = "d.m.Y"
SHORT_DATETIME_FORMAT = "d.m.Y H:i"
FIRST_DAY_OF_WEEK = 1
DATE_INPUT_FORMATS = ["%d.%m.%Y", "%Y-%m-%d"]
DECIMAL_SEPARATOR = ","
THOUSAND_SEPARATOR = "\xa0"
NUMBER_GROUPING = 3
