# Generated by Django 5.2.17 on 2026-09-28 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
        ('genealogy', '0003_marriage_day_marriage_month_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='full name')),
                ('how_met', models.CharField(blank=True, choices=[('classmate', 'Classmate'), ('coursemate', 'University friend'), ('colleague', 'Colleague'), ('neighbour', 'Neighbour'), ('childhood', 'Childhood friend'), ('army', 'Served together in the army'), ('family', 'Family friend'), ('other', 'Other')], max_length=20, verbose_name='how they know each other')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='phone')),
                ('birth_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='year of birth')),
                ('birth_month', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='month of birth')),
                ('birth_day', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='day of birth')),
                ('note', models.TextField(blank=True, verbose_name='notes')),
                ('search_key', models.TextField(blank=True, default='', editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='genealogy.person', verbose_name='whose friend')),
            ],
            options={
                'verbose_name': 'friend',
                'verbose_name_plural': 'friends',
                'ordering': ['name', 'id'],
            },
        ),
    ]
