# Generated by Django 5.2.17 on 2026-09-28 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotState',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='reminders are on')),
                ('days_before', models.PositiveSmallIntegerField(choices=[(0, 'On the day'), (1, 'One day before'), (3, 'Three days before'), (7, 'One week before')], default=1, verbose_name='remind in advance')),
                ('birthdays', models.BooleanField(default=True, verbose_name='birthdays of relatives')),
                ('friends', models.BooleanField(default=True, verbose_name='birthdays of friends')),
                ('anniversaries', models.BooleanField(default=True, verbose_name='wedding anniversaries')),
                ('memorials', models.BooleanField(default=True, verbose_name='memorial days')),
                ('events', models.BooleanField(default=True, verbose_name='family events')),
                ('muchal', models.BooleanField(default=True, verbose_name='muchal years')),
                ('telegram_enabled', models.BooleanField(default=False, verbose_name='send to Telegram')),
                ('telegram_chat_id', models.BigIntegerField(blank=True, null=True)),
                ('telegram_name', models.CharField(blank=True, max_length=100)),
                ('telegram_token', models.CharField(blank=True, db_index=True, max_length=40)),
                ('telegram_token_at', models.DateTimeField(blank=True, null=True)),
                ('send_hour', models.PositiveSmallIntegerField(default=8, verbose_name='send at (hour)')),
                ('last_generated', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notify', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification settings',
                'verbose_name_plural': 'notification settings',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=160)),
                ('kind', models.CharField(max_length=30)),
                ('params', models.JSONField(default=dict)),
                ('url', models.CharField(blank=True, max_length=300)),
                ('occasion_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('telegram_sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'key'), name='unique_notification_key')],
            },
        ),
    ]
